<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'sebastianbergmann\\comparator\\classwithtostring' => '/_files/ClassWithToString.php',
                'sebastianbergmann\\comparator\\testclass' => '/_files/TestClass.php',
                'sebastianbergmann\\comparator\\testclasscomparator' => '/_files/TestClassComparator.php',
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd